version: "3"

services:
  nextjs:
    build: .
    restart: unless-stopped
    ports:
      - "80:3000"
    environment:
      - DATABASE_URL
    depends_on:
      - postgres
  postgres:
    image: postgres:9.5-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: phones
      POSTGRES_PASSWORD: phones123456
